#!/usr/bin/env node
var colors = require('colors'),
    fmt = require('util').format,
    parallelize = require('./lib/parallelizer').parallelize,
    program = require('commander');


function main() {
  program
    .description('Run a list of tasks in parallel')
    .usage('--cwd /path/to/cwd ' +
           '--format "some mocha command %s" ' +
           '--tasks "one_test.js two_test.js three_test.js"')
    .version('0.0.1')
    .option('-d, --cwd [cwd]', 'directory to execute tasks')
    .option('-f, --format [format]', 'template for tasks')
    .option('-t, --tasks [tasks]', 'list of tasks')
    .parse(process.argv);

  var format = program.format || '%s'
      tasks = program.tasks.split(/\s+/).map(function(task) {
        return fmt(format, task);
      });

  var opts = {};
  if (program.cwd) {
    opts.cwd = program.cwd;
  }

  parallelize(tasks, opts);
}


if (require.main === module) {
  main();
}
